# This is a basic workflow that is manually triggered
name: Buil the docker image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell cmds
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t nginx-cons-img .
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_TOKEN }}

        #username: ${{ secrets.DOCKERHUB_USERNAME }}
        #password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DIGITALOCEAN_USERNAME }}/nginx-cons-img:latest
        #tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-cons-img:latest
        #tags: ${{ secrets.DOCKERHUB_USERNAME }}/flowiseai/nginx-cons-img:latest
    
    - name: Run Docker container
      run: |
          docker pull ${{ secrets.DIGITALOCEAN_USERNAME }}/nginx-cons-img
          docker run -d -p 8087:80 --name my-nginx-con  ${{ secrets.DIGITALOCEAN_USERNAME }}/nginx-cons-img:latest

          #docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nginx-cons-img
          #docker run -d -p 8087:80 --name my-nginx-con  ${{ secrets.DOCKERHUB_USERNAME }}/nginx-cons-img:latest
