# This is a basic workflow that is manually triggered
name: Buil the docker image

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    # Inputs the workflow accepts.
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell cmds
    - uses: actions/checkout@v3

      # Authenticate with DigitalOcean Container Registry using doctl
    - name: Authenticate with DigitalOcean Container Registry
      run: doctl auth init --access-token ${{ secrets.DIGITALOCEAN_API_TOKEN }}
Use: The command is used in a GitHub Actions workflow to authenticate the doctl command-line tool with DigitalOcean.

      # Build the Docker image
    - name: Build Docker image
      run: docker build -t nginx-cons-img .

      # Tag the Docker image for DigitalOcean Container Registry
    - name: Tag Docker image for DigitalOcean Container Registry
      run: docker tag nginx-cons-img registry.digitalocean.com/maslow--registry/nginx-cons-img:latest
